// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package io.github.hizhangbo.netty.protobuf.exp2;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ParentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Parent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Parent.ChildType child_type = 1;</code>
     * @return The enum numeric value on the wire for childType.
     */
    int getChildTypeValue();
    /**
     * <code>.Parent.ChildType child_type = 1;</code>
     * @return The childType.
     */
    io.github.hizhangbo.netty.protobuf.exp2.Message.Parent.ChildType getChildType();

    /**
     * <code>.Child1 child1 = 2;</code>
     * @return Whether the child1 field is set.
     */
    boolean hasChild1();
    /**
     * <code>.Child1 child1 = 2;</code>
     * @return The child1.
     */
    io.github.hizhangbo.netty.protobuf.exp2.Message.Child1 getChild1();
    /**
     * <code>.Child1 child1 = 2;</code>
     */
    io.github.hizhangbo.netty.protobuf.exp2.Message.Child1OrBuilder getChild1OrBuilder();

    /**
     * <code>.Child2 child2 = 3;</code>
     * @return Whether the child2 field is set.
     */
    boolean hasChild2();
    /**
     * <code>.Child2 child2 = 3;</code>
     * @return The child2.
     */
    io.github.hizhangbo.netty.protobuf.exp2.Message.Child2 getChild2();
    /**
     * <code>.Child2 child2 = 3;</code>
     */
    io.github.hizhangbo.netty.protobuf.exp2.Message.Child2OrBuilder getChild2OrBuilder();

    public io.github.hizhangbo.netty.protobuf.exp2.Message.Parent.DataBodyCase getDataBodyCase();
  }
  /**
   * Protobuf type {@code Parent}
   */
  public  static final class Parent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Parent)
      ParentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Parent.newBuilder() to construct.
    private Parent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Parent() {
      childType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Parent();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Parent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              childType_ = rawValue;
              break;
            }
            case 18: {
              io.github.hizhangbo.netty.protobuf.exp2.Message.Child1.Builder subBuilder = null;
              if (dataBodyCase_ == 2) {
                subBuilder = ((io.github.hizhangbo.netty.protobuf.exp2.Message.Child1) dataBody_).toBuilder();
              }
              dataBody_ =
                  input.readMessage(io.github.hizhangbo.netty.protobuf.exp2.Message.Child1.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((io.github.hizhangbo.netty.protobuf.exp2.Message.Child1) dataBody_);
                dataBody_ = subBuilder.buildPartial();
              }
              dataBodyCase_ = 2;
              break;
            }
            case 26: {
              io.github.hizhangbo.netty.protobuf.exp2.Message.Child2.Builder subBuilder = null;
              if (dataBodyCase_ == 3) {
                subBuilder = ((io.github.hizhangbo.netty.protobuf.exp2.Message.Child2) dataBody_).toBuilder();
              }
              dataBody_ =
                  input.readMessage(io.github.hizhangbo.netty.protobuf.exp2.Message.Child2.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((io.github.hizhangbo.netty.protobuf.exp2.Message.Child2) dataBody_);
                dataBody_ = subBuilder.buildPartial();
              }
              dataBodyCase_ = 3;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.hizhangbo.netty.protobuf.exp2.Message.internal_static_Parent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.hizhangbo.netty.protobuf.exp2.Message.internal_static_Parent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.hizhangbo.netty.protobuf.exp2.Message.Parent.class, io.github.hizhangbo.netty.protobuf.exp2.Message.Parent.Builder.class);
    }

    /**
     * Protobuf enum {@code Parent.ChildType}
     */
    public enum ChildType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>Child1 = 0;</code>
       */
      Child1(0),
      /**
       * <code>Child2 = 1;</code>
       */
      Child2(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>Child1 = 0;</code>
       */
      public static final int Child1_VALUE = 0;
      /**
       * <code>Child2 = 1;</code>
       */
      public static final int Child2_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ChildType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static ChildType forNumber(int value) {
        switch (value) {
          case 0: return Child1;
          case 1: return Child2;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ChildType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ChildType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ChildType>() {
              public ChildType findValueByNumber(int number) {
                return ChildType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return io.github.hizhangbo.netty.protobuf.exp2.Message.Parent.getDescriptor().getEnumTypes().get(0);
      }

      private static final ChildType[] VALUES = values();

      public static ChildType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ChildType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Parent.ChildType)
    }

    private int dataBodyCase_ = 0;
    private java.lang.Object dataBody_;
    public enum DataBodyCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      CHILD1(2),
      CHILD2(3),
      DATABODY_NOT_SET(0);
      private final int value;
      private DataBodyCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataBodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataBodyCase forNumber(int value) {
        switch (value) {
          case 2: return CHILD1;
          case 3: return CHILD2;
          case 0: return DATABODY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DataBodyCase
    getDataBodyCase() {
      return DataBodyCase.forNumber(
          dataBodyCase_);
    }

    public static final int CHILD_TYPE_FIELD_NUMBER = 1;
    private int childType_;
    /**
     * <code>.Parent.ChildType child_type = 1;</code>
     * @return The enum numeric value on the wire for childType.
     */
    public int getChildTypeValue() {
      return childType_;
    }
    /**
     * <code>.Parent.ChildType child_type = 1;</code>
     * @return The childType.
     */
    public io.github.hizhangbo.netty.protobuf.exp2.Message.Parent.ChildType getChildType() {
      @SuppressWarnings("deprecation")
      io.github.hizhangbo.netty.protobuf.exp2.Message.Parent.ChildType result = io.github.hizhangbo.netty.protobuf.exp2.Message.Parent.ChildType.valueOf(childType_);
      return result == null ? io.github.hizhangbo.netty.protobuf.exp2.Message.Parent.ChildType.UNRECOGNIZED : result;
    }

    public static final int CHILD1_FIELD_NUMBER = 2;
    /**
     * <code>.Child1 child1 = 2;</code>
     * @return Whether the child1 field is set.
     */
    public boolean hasChild1() {
      return dataBodyCase_ == 2;
    }
    /**
     * <code>.Child1 child1 = 2;</code>
     * @return The child1.
     */
    public io.github.hizhangbo.netty.protobuf.exp2.Message.Child1 getChild1() {
      if (dataBodyCase_ == 2) {
         return (io.github.hizhangbo.netty.protobuf.exp2.Message.Child1) dataBody_;
      }
      return io.github.hizhangbo.netty.protobuf.exp2.Message.Child1.getDefaultInstance();
    }
    /**
     * <code>.Child1 child1 = 2;</code>
     */
    public io.github.hizhangbo.netty.protobuf.exp2.Message.Child1OrBuilder getChild1OrBuilder() {
      if (dataBodyCase_ == 2) {
         return (io.github.hizhangbo.netty.protobuf.exp2.Message.Child1) dataBody_;
      }
      return io.github.hizhangbo.netty.protobuf.exp2.Message.Child1.getDefaultInstance();
    }

    public static final int CHILD2_FIELD_NUMBER = 3;
    /**
     * <code>.Child2 child2 = 3;</code>
     * @return Whether the child2 field is set.
     */
    public boolean hasChild2() {
      return dataBodyCase_ == 3;
    }
    /**
     * <code>.Child2 child2 = 3;</code>
     * @return The child2.
     */
    public io.github.hizhangbo.netty.protobuf.exp2.Message.Child2 getChild2() {
      if (dataBodyCase_ == 3) {
         return (io.github.hizhangbo.netty.protobuf.exp2.Message.Child2) dataBody_;
      }
      return io.github.hizhangbo.netty.protobuf.exp2.Message.Child2.getDefaultInstance();
    }
    /**
     * <code>.Child2 child2 = 3;</code>
     */
    public io.github.hizhangbo.netty.protobuf.exp2.Message.Child2OrBuilder getChild2OrBuilder() {
      if (dataBodyCase_ == 3) {
         return (io.github.hizhangbo.netty.protobuf.exp2.Message.Child2) dataBody_;
      }
      return io.github.hizhangbo.netty.protobuf.exp2.Message.Child2.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (childType_ != io.github.hizhangbo.netty.protobuf.exp2.Message.Parent.ChildType.Child1.getNumber()) {
        output.writeEnum(1, childType_);
      }
      if (dataBodyCase_ == 2) {
        output.writeMessage(2, (io.github.hizhangbo.netty.protobuf.exp2.Message.Child1) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        output.writeMessage(3, (io.github.hizhangbo.netty.protobuf.exp2.Message.Child2) dataBody_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (childType_ != io.github.hizhangbo.netty.protobuf.exp2.Message.Parent.ChildType.Child1.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, childType_);
      }
      if (dataBodyCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (io.github.hizhangbo.netty.protobuf.exp2.Message.Child1) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (io.github.hizhangbo.netty.protobuf.exp2.Message.Child2) dataBody_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.github.hizhangbo.netty.protobuf.exp2.Message.Parent)) {
        return super.equals(obj);
      }
      io.github.hizhangbo.netty.protobuf.exp2.Message.Parent other = (io.github.hizhangbo.netty.protobuf.exp2.Message.Parent) obj;

      if (childType_ != other.childType_) return false;
      if (!getDataBodyCase().equals(other.getDataBodyCase())) return false;
      switch (dataBodyCase_) {
        case 2:
          if (!getChild1()
              .equals(other.getChild1())) return false;
          break;
        case 3:
          if (!getChild2()
              .equals(other.getChild2())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CHILD_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + childType_;
      switch (dataBodyCase_) {
        case 2:
          hash = (37 * hash) + CHILD1_FIELD_NUMBER;
          hash = (53 * hash) + getChild1().hashCode();
          break;
        case 3:
          hash = (37 * hash) + CHILD2_FIELD_NUMBER;
          hash = (53 * hash) + getChild2().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.github.hizhangbo.netty.protobuf.exp2.Message.Parent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.hizhangbo.netty.protobuf.exp2.Message.Parent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.hizhangbo.netty.protobuf.exp2.Message.Parent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.hizhangbo.netty.protobuf.exp2.Message.Parent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.hizhangbo.netty.protobuf.exp2.Message.Parent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.hizhangbo.netty.protobuf.exp2.Message.Parent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.hizhangbo.netty.protobuf.exp2.Message.Parent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.hizhangbo.netty.protobuf.exp2.Message.Parent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.hizhangbo.netty.protobuf.exp2.Message.Parent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.github.hizhangbo.netty.protobuf.exp2.Message.Parent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.hizhangbo.netty.protobuf.exp2.Message.Parent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.hizhangbo.netty.protobuf.exp2.Message.Parent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.github.hizhangbo.netty.protobuf.exp2.Message.Parent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Parent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Parent)
        io.github.hizhangbo.netty.protobuf.exp2.Message.ParentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.hizhangbo.netty.protobuf.exp2.Message.internal_static_Parent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.hizhangbo.netty.protobuf.exp2.Message.internal_static_Parent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.hizhangbo.netty.protobuf.exp2.Message.Parent.class, io.github.hizhangbo.netty.protobuf.exp2.Message.Parent.Builder.class);
      }

      // Construct using io.github.hizhangbo.netty.protobuf.exp2.Message.Parent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        childType_ = 0;

        dataBodyCase_ = 0;
        dataBody_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.hizhangbo.netty.protobuf.exp2.Message.internal_static_Parent_descriptor;
      }

      @java.lang.Override
      public io.github.hizhangbo.netty.protobuf.exp2.Message.Parent getDefaultInstanceForType() {
        return io.github.hizhangbo.netty.protobuf.exp2.Message.Parent.getDefaultInstance();
      }

      @java.lang.Override
      public io.github.hizhangbo.netty.protobuf.exp2.Message.Parent build() {
        io.github.hizhangbo.netty.protobuf.exp2.Message.Parent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.github.hizhangbo.netty.protobuf.exp2.Message.Parent buildPartial() {
        io.github.hizhangbo.netty.protobuf.exp2.Message.Parent result = new io.github.hizhangbo.netty.protobuf.exp2.Message.Parent(this);
        result.childType_ = childType_;
        if (dataBodyCase_ == 2) {
          if (child1Builder_ == null) {
            result.dataBody_ = dataBody_;
          } else {
            result.dataBody_ = child1Builder_.build();
          }
        }
        if (dataBodyCase_ == 3) {
          if (child2Builder_ == null) {
            result.dataBody_ = dataBody_;
          } else {
            result.dataBody_ = child2Builder_.build();
          }
        }
        result.dataBodyCase_ = dataBodyCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.hizhangbo.netty.protobuf.exp2.Message.Parent) {
          return mergeFrom((io.github.hizhangbo.netty.protobuf.exp2.Message.Parent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.hizhangbo.netty.protobuf.exp2.Message.Parent other) {
        if (other == io.github.hizhangbo.netty.protobuf.exp2.Message.Parent.getDefaultInstance()) return this;
        if (other.childType_ != 0) {
          setChildTypeValue(other.getChildTypeValue());
        }
        switch (other.getDataBodyCase()) {
          case CHILD1: {
            mergeChild1(other.getChild1());
            break;
          }
          case CHILD2: {
            mergeChild2(other.getChild2());
            break;
          }
          case DATABODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.github.hizhangbo.netty.protobuf.exp2.Message.Parent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.github.hizhangbo.netty.protobuf.exp2.Message.Parent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int dataBodyCase_ = 0;
      private java.lang.Object dataBody_;
      public DataBodyCase
          getDataBodyCase() {
        return DataBodyCase.forNumber(
            dataBodyCase_);
      }

      public Builder clearDataBody() {
        dataBodyCase_ = 0;
        dataBody_ = null;
        onChanged();
        return this;
      }


      private int childType_ = 0;
      /**
       * <code>.Parent.ChildType child_type = 1;</code>
       * @return The enum numeric value on the wire for childType.
       */
      public int getChildTypeValue() {
        return childType_;
      }
      /**
       * <code>.Parent.ChildType child_type = 1;</code>
       * @param value The enum numeric value on the wire for childType to set.
       * @return This builder for chaining.
       */
      public Builder setChildTypeValue(int value) {
        childType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Parent.ChildType child_type = 1;</code>
       * @return The childType.
       */
      public io.github.hizhangbo.netty.protobuf.exp2.Message.Parent.ChildType getChildType() {
        @SuppressWarnings("deprecation")
        io.github.hizhangbo.netty.protobuf.exp2.Message.Parent.ChildType result = io.github.hizhangbo.netty.protobuf.exp2.Message.Parent.ChildType.valueOf(childType_);
        return result == null ? io.github.hizhangbo.netty.protobuf.exp2.Message.Parent.ChildType.UNRECOGNIZED : result;
      }
      /**
       * <code>.Parent.ChildType child_type = 1;</code>
       * @param value The childType to set.
       * @return This builder for chaining.
       */
      public Builder setChildType(io.github.hizhangbo.netty.protobuf.exp2.Message.Parent.ChildType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        childType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Parent.ChildType child_type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearChildType() {
        
        childType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          io.github.hizhangbo.netty.protobuf.exp2.Message.Child1, io.github.hizhangbo.netty.protobuf.exp2.Message.Child1.Builder, io.github.hizhangbo.netty.protobuf.exp2.Message.Child1OrBuilder> child1Builder_;
      /**
       * <code>.Child1 child1 = 2;</code>
       * @return Whether the child1 field is set.
       */
      public boolean hasChild1() {
        return dataBodyCase_ == 2;
      }
      /**
       * <code>.Child1 child1 = 2;</code>
       * @return The child1.
       */
      public io.github.hizhangbo.netty.protobuf.exp2.Message.Child1 getChild1() {
        if (child1Builder_ == null) {
          if (dataBodyCase_ == 2) {
            return (io.github.hizhangbo.netty.protobuf.exp2.Message.Child1) dataBody_;
          }
          return io.github.hizhangbo.netty.protobuf.exp2.Message.Child1.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 2) {
            return child1Builder_.getMessage();
          }
          return io.github.hizhangbo.netty.protobuf.exp2.Message.Child1.getDefaultInstance();
        }
      }
      /**
       * <code>.Child1 child1 = 2;</code>
       */
      public Builder setChild1(io.github.hizhangbo.netty.protobuf.exp2.Message.Child1 value) {
        if (child1Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          child1Builder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.Child1 child1 = 2;</code>
       */
      public Builder setChild1(
          io.github.hizhangbo.netty.protobuf.exp2.Message.Child1.Builder builderForValue) {
        if (child1Builder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          child1Builder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.Child1 child1 = 2;</code>
       */
      public Builder mergeChild1(io.github.hizhangbo.netty.protobuf.exp2.Message.Child1 value) {
        if (child1Builder_ == null) {
          if (dataBodyCase_ == 2 &&
              dataBody_ != io.github.hizhangbo.netty.protobuf.exp2.Message.Child1.getDefaultInstance()) {
            dataBody_ = io.github.hizhangbo.netty.protobuf.exp2.Message.Child1.newBuilder((io.github.hizhangbo.netty.protobuf.exp2.Message.Child1) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 2) {
            child1Builder_.mergeFrom(value);
          }
          child1Builder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.Child1 child1 = 2;</code>
       */
      public Builder clearChild1() {
        if (child1Builder_ == null) {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          child1Builder_.clear();
        }
        return this;
      }
      /**
       * <code>.Child1 child1 = 2;</code>
       */
      public io.github.hizhangbo.netty.protobuf.exp2.Message.Child1.Builder getChild1Builder() {
        return getChild1FieldBuilder().getBuilder();
      }
      /**
       * <code>.Child1 child1 = 2;</code>
       */
      public io.github.hizhangbo.netty.protobuf.exp2.Message.Child1OrBuilder getChild1OrBuilder() {
        if ((dataBodyCase_ == 2) && (child1Builder_ != null)) {
          return child1Builder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 2) {
            return (io.github.hizhangbo.netty.protobuf.exp2.Message.Child1) dataBody_;
          }
          return io.github.hizhangbo.netty.protobuf.exp2.Message.Child1.getDefaultInstance();
        }
      }
      /**
       * <code>.Child1 child1 = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          io.github.hizhangbo.netty.protobuf.exp2.Message.Child1, io.github.hizhangbo.netty.protobuf.exp2.Message.Child1.Builder, io.github.hizhangbo.netty.protobuf.exp2.Message.Child1OrBuilder> 
          getChild1FieldBuilder() {
        if (child1Builder_ == null) {
          if (!(dataBodyCase_ == 2)) {
            dataBody_ = io.github.hizhangbo.netty.protobuf.exp2.Message.Child1.getDefaultInstance();
          }
          child1Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
              io.github.hizhangbo.netty.protobuf.exp2.Message.Child1, io.github.hizhangbo.netty.protobuf.exp2.Message.Child1.Builder, io.github.hizhangbo.netty.protobuf.exp2.Message.Child1OrBuilder>(
                  (io.github.hizhangbo.netty.protobuf.exp2.Message.Child1) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 2;
        onChanged();;
        return child1Builder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          io.github.hizhangbo.netty.protobuf.exp2.Message.Child2, io.github.hizhangbo.netty.protobuf.exp2.Message.Child2.Builder, io.github.hizhangbo.netty.protobuf.exp2.Message.Child2OrBuilder> child2Builder_;
      /**
       * <code>.Child2 child2 = 3;</code>
       * @return Whether the child2 field is set.
       */
      public boolean hasChild2() {
        return dataBodyCase_ == 3;
      }
      /**
       * <code>.Child2 child2 = 3;</code>
       * @return The child2.
       */
      public io.github.hizhangbo.netty.protobuf.exp2.Message.Child2 getChild2() {
        if (child2Builder_ == null) {
          if (dataBodyCase_ == 3) {
            return (io.github.hizhangbo.netty.protobuf.exp2.Message.Child2) dataBody_;
          }
          return io.github.hizhangbo.netty.protobuf.exp2.Message.Child2.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 3) {
            return child2Builder_.getMessage();
          }
          return io.github.hizhangbo.netty.protobuf.exp2.Message.Child2.getDefaultInstance();
        }
      }
      /**
       * <code>.Child2 child2 = 3;</code>
       */
      public Builder setChild2(io.github.hizhangbo.netty.protobuf.exp2.Message.Child2 value) {
        if (child2Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          child2Builder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.Child2 child2 = 3;</code>
       */
      public Builder setChild2(
          io.github.hizhangbo.netty.protobuf.exp2.Message.Child2.Builder builderForValue) {
        if (child2Builder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          child2Builder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.Child2 child2 = 3;</code>
       */
      public Builder mergeChild2(io.github.hizhangbo.netty.protobuf.exp2.Message.Child2 value) {
        if (child2Builder_ == null) {
          if (dataBodyCase_ == 3 &&
              dataBody_ != io.github.hizhangbo.netty.protobuf.exp2.Message.Child2.getDefaultInstance()) {
            dataBody_ = io.github.hizhangbo.netty.protobuf.exp2.Message.Child2.newBuilder((io.github.hizhangbo.netty.protobuf.exp2.Message.Child2) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 3) {
            child2Builder_.mergeFrom(value);
          }
          child2Builder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.Child2 child2 = 3;</code>
       */
      public Builder clearChild2() {
        if (child2Builder_ == null) {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          child2Builder_.clear();
        }
        return this;
      }
      /**
       * <code>.Child2 child2 = 3;</code>
       */
      public io.github.hizhangbo.netty.protobuf.exp2.Message.Child2.Builder getChild2Builder() {
        return getChild2FieldBuilder().getBuilder();
      }
      /**
       * <code>.Child2 child2 = 3;</code>
       */
      public io.github.hizhangbo.netty.protobuf.exp2.Message.Child2OrBuilder getChild2OrBuilder() {
        if ((dataBodyCase_ == 3) && (child2Builder_ != null)) {
          return child2Builder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 3) {
            return (io.github.hizhangbo.netty.protobuf.exp2.Message.Child2) dataBody_;
          }
          return io.github.hizhangbo.netty.protobuf.exp2.Message.Child2.getDefaultInstance();
        }
      }
      /**
       * <code>.Child2 child2 = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          io.github.hizhangbo.netty.protobuf.exp2.Message.Child2, io.github.hizhangbo.netty.protobuf.exp2.Message.Child2.Builder, io.github.hizhangbo.netty.protobuf.exp2.Message.Child2OrBuilder> 
          getChild2FieldBuilder() {
        if (child2Builder_ == null) {
          if (!(dataBodyCase_ == 3)) {
            dataBody_ = io.github.hizhangbo.netty.protobuf.exp2.Message.Child2.getDefaultInstance();
          }
          child2Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
              io.github.hizhangbo.netty.protobuf.exp2.Message.Child2, io.github.hizhangbo.netty.protobuf.exp2.Message.Child2.Builder, io.github.hizhangbo.netty.protobuf.exp2.Message.Child2OrBuilder>(
                  (io.github.hizhangbo.netty.protobuf.exp2.Message.Child2) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 3;
        onChanged();;
        return child2Builder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Parent)
    }

    // @@protoc_insertion_point(class_scope:Parent)
    private static final io.github.hizhangbo.netty.protobuf.exp2.Message.Parent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.github.hizhangbo.netty.protobuf.exp2.Message.Parent();
    }

    public static io.github.hizhangbo.netty.protobuf.exp2.Message.Parent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Parent>
        PARSER = new com.google.protobuf.AbstractParser<Parent>() {
      @java.lang.Override
      public Parent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Parent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Parent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Parent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.github.hizhangbo.netty.protobuf.exp2.Message.Parent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Child1OrBuilder extends
      // @@protoc_insertion_point(interface_extends:Child1)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string email = 3;</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 3;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();
  }
  /**
   * Protobuf type {@code Child1}
   */
  public  static final class Child1 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Child1)
      Child1OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Child1.newBuilder() to construct.
    private Child1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Child1() {
      name_ = "";
      email_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Child1();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Child1(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.hizhangbo.netty.protobuf.exp2.Message.internal_static_Child1_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.hizhangbo.netty.protobuf.exp2.Message.internal_static_Child1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.hizhangbo.netty.protobuf.exp2.Message.Child1.class, io.github.hizhangbo.netty.protobuf.exp2.Message.Child1.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    private volatile java.lang.Object email_;
    /**
     * <code>string email = 3;</code>
     * @return The email.
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 3;</code>
     * @return The bytes for email.
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.github.hizhangbo.netty.protobuf.exp2.Message.Child1)) {
        return super.equals(obj);
      }
      io.github.hizhangbo.netty.protobuf.exp2.Message.Child1 other = (io.github.hizhangbo.netty.protobuf.exp2.Message.Child1) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getEmail()
          .equals(other.getEmail())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.github.hizhangbo.netty.protobuf.exp2.Message.Child1 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.hizhangbo.netty.protobuf.exp2.Message.Child1 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.hizhangbo.netty.protobuf.exp2.Message.Child1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.hizhangbo.netty.protobuf.exp2.Message.Child1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.hizhangbo.netty.protobuf.exp2.Message.Child1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.hizhangbo.netty.protobuf.exp2.Message.Child1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.hizhangbo.netty.protobuf.exp2.Message.Child1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.hizhangbo.netty.protobuf.exp2.Message.Child1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.hizhangbo.netty.protobuf.exp2.Message.Child1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.github.hizhangbo.netty.protobuf.exp2.Message.Child1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.hizhangbo.netty.protobuf.exp2.Message.Child1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.hizhangbo.netty.protobuf.exp2.Message.Child1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.github.hizhangbo.netty.protobuf.exp2.Message.Child1 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Child1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Child1)
        io.github.hizhangbo.netty.protobuf.exp2.Message.Child1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.hizhangbo.netty.protobuf.exp2.Message.internal_static_Child1_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.hizhangbo.netty.protobuf.exp2.Message.internal_static_Child1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.hizhangbo.netty.protobuf.exp2.Message.Child1.class, io.github.hizhangbo.netty.protobuf.exp2.Message.Child1.Builder.class);
      }

      // Construct using io.github.hizhangbo.netty.protobuf.exp2.Message.Child1.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        email_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.hizhangbo.netty.protobuf.exp2.Message.internal_static_Child1_descriptor;
      }

      @java.lang.Override
      public io.github.hizhangbo.netty.protobuf.exp2.Message.Child1 getDefaultInstanceForType() {
        return io.github.hizhangbo.netty.protobuf.exp2.Message.Child1.getDefaultInstance();
      }

      @java.lang.Override
      public io.github.hizhangbo.netty.protobuf.exp2.Message.Child1 build() {
        io.github.hizhangbo.netty.protobuf.exp2.Message.Child1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.github.hizhangbo.netty.protobuf.exp2.Message.Child1 buildPartial() {
        io.github.hizhangbo.netty.protobuf.exp2.Message.Child1 result = new io.github.hizhangbo.netty.protobuf.exp2.Message.Child1(this);
        result.id_ = id_;
        result.name_ = name_;
        result.email_ = email_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.hizhangbo.netty.protobuf.exp2.Message.Child1) {
          return mergeFrom((io.github.hizhangbo.netty.protobuf.exp2.Message.Child1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.hizhangbo.netty.protobuf.exp2.Message.Child1 other) {
        if (other == io.github.hizhangbo.netty.protobuf.exp2.Message.Child1.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.github.hizhangbo.netty.protobuf.exp2.Message.Child1 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.github.hizhangbo.netty.protobuf.exp2.Message.Child1) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 3;</code>
       * @return The email.
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       * @return The bytes for email.
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Child1)
    }

    // @@protoc_insertion_point(class_scope:Child1)
    private static final io.github.hizhangbo.netty.protobuf.exp2.Message.Child1 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.github.hizhangbo.netty.protobuf.exp2.Message.Child1();
    }

    public static io.github.hizhangbo.netty.protobuf.exp2.Message.Child1 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Child1>
        PARSER = new com.google.protobuf.AbstractParser<Child1>() {
      @java.lang.Override
      public Child1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Child1(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Child1> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Child1> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.github.hizhangbo.netty.protobuf.exp2.Message.Child1 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Child2OrBuilder extends
      // @@protoc_insertion_point(interface_extends:Child2)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 age = 2;</code>
     * @return The age.
     */
    int getAge();
  }
  /**
   * Protobuf type {@code Child2}
   */
  public  static final class Child2 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Child2)
      Child2OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Child2.newBuilder() to construct.
    private Child2(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Child2() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Child2();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Child2(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              age_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.hizhangbo.netty.protobuf.exp2.Message.internal_static_Child2_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.hizhangbo.netty.protobuf.exp2.Message.internal_static_Child2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.hizhangbo.netty.protobuf.exp2.Message.Child2.class, io.github.hizhangbo.netty.protobuf.exp2.Message.Child2.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <code>int32 age = 2;</code>
     * @return The age.
     */
    public int getAge() {
      return age_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (age_ != 0) {
        output.writeInt32(2, age_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.github.hizhangbo.netty.protobuf.exp2.Message.Child2)) {
        return super.equals(obj);
      }
      io.github.hizhangbo.netty.protobuf.exp2.Message.Child2 other = (io.github.hizhangbo.netty.protobuf.exp2.Message.Child2) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (getAge()
          != other.getAge()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.github.hizhangbo.netty.protobuf.exp2.Message.Child2 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.hizhangbo.netty.protobuf.exp2.Message.Child2 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.hizhangbo.netty.protobuf.exp2.Message.Child2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.hizhangbo.netty.protobuf.exp2.Message.Child2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.hizhangbo.netty.protobuf.exp2.Message.Child2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.hizhangbo.netty.protobuf.exp2.Message.Child2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.hizhangbo.netty.protobuf.exp2.Message.Child2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.hizhangbo.netty.protobuf.exp2.Message.Child2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.hizhangbo.netty.protobuf.exp2.Message.Child2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.github.hizhangbo.netty.protobuf.exp2.Message.Child2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.hizhangbo.netty.protobuf.exp2.Message.Child2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.hizhangbo.netty.protobuf.exp2.Message.Child2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.github.hizhangbo.netty.protobuf.exp2.Message.Child2 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Child2}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Child2)
        io.github.hizhangbo.netty.protobuf.exp2.Message.Child2OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.hizhangbo.netty.protobuf.exp2.Message.internal_static_Child2_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.hizhangbo.netty.protobuf.exp2.Message.internal_static_Child2_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.hizhangbo.netty.protobuf.exp2.Message.Child2.class, io.github.hizhangbo.netty.protobuf.exp2.Message.Child2.Builder.class);
      }

      // Construct using io.github.hizhangbo.netty.protobuf.exp2.Message.Child2.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        age_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.hizhangbo.netty.protobuf.exp2.Message.internal_static_Child2_descriptor;
      }

      @java.lang.Override
      public io.github.hizhangbo.netty.protobuf.exp2.Message.Child2 getDefaultInstanceForType() {
        return io.github.hizhangbo.netty.protobuf.exp2.Message.Child2.getDefaultInstance();
      }

      @java.lang.Override
      public io.github.hizhangbo.netty.protobuf.exp2.Message.Child2 build() {
        io.github.hizhangbo.netty.protobuf.exp2.Message.Child2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.github.hizhangbo.netty.protobuf.exp2.Message.Child2 buildPartial() {
        io.github.hizhangbo.netty.protobuf.exp2.Message.Child2 result = new io.github.hizhangbo.netty.protobuf.exp2.Message.Child2(this);
        result.name_ = name_;
        result.age_ = age_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.hizhangbo.netty.protobuf.exp2.Message.Child2) {
          return mergeFrom((io.github.hizhangbo.netty.protobuf.exp2.Message.Child2)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.hizhangbo.netty.protobuf.exp2.Message.Child2 other) {
        if (other == io.github.hizhangbo.netty.protobuf.exp2.Message.Child2.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.github.hizhangbo.netty.protobuf.exp2.Message.Child2 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.github.hizhangbo.netty.protobuf.exp2.Message.Child2) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>int32 age = 2;</code>
       * @return The age.
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>int32 age = 2;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 age = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Child2)
    }

    // @@protoc_insertion_point(class_scope:Child2)
    private static final io.github.hizhangbo.netty.protobuf.exp2.Message.Child2 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.github.hizhangbo.netty.protobuf.exp2.Message.Child2();
    }

    public static io.github.hizhangbo.netty.protobuf.exp2.Message.Child2 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Child2>
        PARSER = new com.google.protobuf.AbstractParser<Child2>() {
      @java.lang.Override
      public Child2 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Child2(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Child2> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Child2> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.github.hizhangbo.netty.protobuf.exp2.Message.Child2 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Parent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Parent_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Child1_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Child1_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Child2_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Child2_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\"\226\001\n\006Parent\022%\n\nchild_type" +
      "\030\001 \001(\0162\021.Parent.ChildType\022\031\n\006child1\030\002 \001(" +
      "\0132\007.Child1H\000\022\031\n\006child2\030\003 \001(\0132\007.Child2H\000\"" +
      "#\n\tChildType\022\n\n\006Child1\020\000\022\n\n\006Child2\020\001B\n\n\010" +
      "dataBody\"1\n\006Child1\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002" +
      " \001(\t\022\r\n\005email\030\003 \001(\t\"#\n\006Child2\022\014\n\004name\030\001 " +
      "\001(\t\022\013\n\003age\030\002 \001(\005B4\n\'io.github.hizhangbo." +
      "netty.protobuf.exp2B\007MessageH\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Parent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Parent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Parent_descriptor,
        new java.lang.String[] { "ChildType", "Child1", "Child2", "DataBody", });
    internal_static_Child1_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Child1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Child1_descriptor,
        new java.lang.String[] { "Id", "Name", "Email", });
    internal_static_Child2_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Child2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Child2_descriptor,
        new java.lang.String[] { "Name", "Age", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
